<a href="https://colab.research.google.com/github/Rainmier/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python program to inverse and transpose

In [1]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
A=np.array([[1,2],[4,7]])
B=(np.linalg.inv(A))
print(B)

[[-7.  2.]
 [ 4. -1.]]


In [3]:
import numpy as np
A=np.array([[1,2],[4,7]])
invA=(np.linalg.inv(A))
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [4]:
C=np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


In [5]:
##Python Program to Transpose a 3x3 Matrix A=([6,1,1],[4,-2,5],[2,8,7])
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B=np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [9]:
#Python Program to Inverse a 3x3 Matrix A=([6,1,1],[4,-2,5],[2,8,7])
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B=(np.linalg.inv(A))
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


## Coding Activity 3

## Create a Python Program to inverse and transpose a 4x4 matrix



## A = ( [6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7] )



In [10]:
#Python Program to Inverse a 4x4 Matrix A=([6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7])
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print(A)
B=(np.linalg.inv(A))
print(B)

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


In [11]:
#Python Program to Transpose a 4x4 Matrix A=([6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7])
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print(A)
B=np.transpose(A)
print(B)

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
