<a href="https://colab.research.google.com/github/Rainmier/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Question 1

In [21]:
import numpy as np

C = np.zeros((5,5))
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##Question 2

In [19]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
diag = np.triu(C)
print(diag)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


##Question 3

In [29]:
C = np.array([[2,4,6,8,10],[1,3,5,7,8],[6,4,2,1,6]])
print(C)

[[ 2  4  6  8 10]
 [ 1  3  5  7  8]
 [ 6  4  2  1  6]]


##Question 4

In [24]:
C_a = np.array([[1,2,3],[2,3,3],[3,4,-2]])
C = np.linalg.inv(C_a) #Inverse of Matrix C
print(C)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5

In [17]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


##Question 6

In [7]:
Equations = np.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]])

Constants = np.array([[[3.4],
                       [8.8],
                       [19.2]]])

roots = np.linalg.inv(Equations) @ Constants
print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
