<a href="https://colab.research.google.com/github/Rainmier/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)
print()
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print()
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(C)
print()
D = np.array([[1,2],[3,4]])
print(D)
print()
dot = np.dot(A,B)
print(dot)
print()
print(D+D)
print()
print(2*C)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [3 4]]

[[22 28]
 [49 64]]

[[2 4]
 [6 8]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [2]:
import numpy as np
A = np.array([5,3,-1])

print('size of array:', A.size)

print('type of array:', type(A))

print('shape of array:', A.shape)

print('dimension of array:', A.ndim)

size of array: 3
type of array: <class 'numpy.ndarray'>
shape of array: (3,)
dimension of array: 1
