<a href="https://colab.research.google.com/github/Rainmier/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)
print()
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print()
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(C)
print()
D = np.array([[1,2],[3,4]])
print(D)
print()
dot = np.dot(A,B)
print(dot)
print()
print(D+D)
print()
print(2*C)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [3 4]]

[[22 28]
 [49 64]]

[[2 4]
 [6 8]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
import numpy as np
A = np.array([5,3,-1])

print(A.size)

print(type(A))

print(A.shape)

print(A.ndim)

3
<class 'numpy.ndarray'>
(3,)
1
