<a href="https://colab.research.google.com/github/Rainmier/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Prelim Exam**

**Question 1**

In [29]:
import numpy as np
c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Question 2**

In [28]:
import numpy as np
c = np.eye(4)
print(c)
print()
print(c*2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


**Question 3**

In [19]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])
cross = np.cross(A,B)
print(cross)

[20 -4 -3]
